import { createThemeContract } from "@macaron-css/core";

export const vars = createThemeContract({
  color: {
    background: null,
    text: null,
    textContrast: null,
    focus: null,
    neutral: null,
    neutralHover: null,
    neutralShadow: null,
    primary: null,
    primaryHover: null,
    primaryShadow: null,
    accent: null,
    accentHover: null,
    accentShadow: null,
    success: null,
    successHover: null,
    successShadow: null,
    info: null,
    infoHover: null,
    infoShadow: null,
    warning: null,
    warningHover: null,
    warningShadow: null,
    danger: null,
    dangerHover: null,
    dangerShadow: null,
    secondary: null,
  },
  spacing: {
    small: null,
    medium: null,
    large: null,
    xlarge: null,
  },
  fluidContainerSizes: {
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
  },
  breakpoints: {
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
  },
  media: {
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
  },
});
